### ISSUE TITLE
VSCode not showing in preferences

### ISSUE THREAD

**Issue by MetaDev** [dotBunny/VSCode#129]
I have installed VSCode through the asset store (I also tried cloning the repo), Unity 5.5.0, latest MONO and Unity Debugger.

I tried restarting everything but the VSCode tab doesn't show in the preferences of Unity

I get this warning:

Assets/VSCode/Plugins/Editor/VSCode.cs(333,18): warning CS0436: The type `dotBunny.Unity.VSCode' conflicts with the imported type of same name'. Ignoring the imported type definition

**Comment by MetaDev** [comment]
It appeared :).

**Comment by MetaDev** [comment]
And it's gone again.

**Comment by ablakey** [comment]
I had this issue today.  By resolving any code errors that were listed in my console, it re-appeared. Seems like it won't fully load if you boot up your project and the compiler hits code errors in any of your project's scripts.

**Comment by reapazor** [comment]
This is a general repeat thing we hear about.

Because the plugin is open source, Unity has to compile it before it shows up in your preferences (for example). We've contemplated making a DLL version, however to date haven't seen a good justification. Also, on the horizon is 5.5's inclusion of VSCode in its pipeline already. At that point this plugin goes into a legacy type approach supporting older users only.
