### ISSUE TITLE
OmniSharp not working

### ISSUE THREAD

**Issue by 0xsven** [dotBunny/VSCode#13]
Hi. 

the flame icon is not showing up at all. OmniSharp features are not working. I read everything I could find.

My Setup:
- I am using Unity 5.2.0f3
- VS Code 0.8.0
- mono version 4.0.4 (latest from here: http://www.mono-project.com/download/ )

Regarding VSCode.cs file:
- VSCode.cs file is in Assets/Plugins/VSCode/Editor
- VS Code > "Enable Integration" is enabled
- I tried all combinations of Force Sync Project, Open Project and Write Launch File
- It opens the correct files and lines of code!
- I can't find a launch.json file anywhere!

Any idea?

**Comment by sorab2142** [comment]
Same problem here

**Comment by bluefallsky** [comment]
BUMP!!
widnow 7 , Unity3d - 5.1.3f1

**Comment by ATBrackeys** [comment]
Same here: Mac, Unity 5.2

**Comment by B2D235** [comment]
My flame icon is showing up, but even after selecting a project it's not working for me.
I've got the latest VSCode plugin downloaded (With the options menu integrated into Unity Prefs)

Windows 10, Unity 5.2.0f3, VSCode 0.8.0, Mono 4.0.3

Here is the OmniSharp log if it helps at all - http://pastebin.com/z8h7STfB

Looks like I'll just have to stick with the the Visual Studio 2015 that is packaged with the new Unity installer for now - it's a shame because this was working for me once upon a time and I love the speed of it all :)

**Comment by reapazor** [comment]
Just writing to say i've got a reproducible case for this now locally. I'll see if i can track down whats going on.

My case actually has issues with some libraries, which might lead me to believe that the libraries cant be read by OmniSharp... in some cases atleast.

**Comment by Abdou23** [comment]
Same problem, the OmniSharp  flame keeps loading and I can't click on it , and the IntelliSense is not working, I'm on Mac, did you guys figure it out ?

**Comment by igarcez** [comment]
I had this problem too, I did lots of things trying to solve it, I think that removing special characters (a 'ó') from the project folder name solved it for me.

**Comment by reapazor** [comment]
The special characters problem is a known issue for Visual Studio Code projects.

**Comment by igarcez** [comment]
Understood

**Comment by reapazor** [comment]
@B2D235 your problem is related to the fact that I force the desired .NET version to 2.0 (what Unity supports). It looks like while you have 4.0+ installed based on your logs, you do not have the older version installed, so when it trys to link against it ...things fall apart. 

My guess at this point is you need to install that, but thats just a rough guess... :)

**Comment by MannyC** [comment]
I was having this issue, and Code was freezing after Omnisharp spat out the errors similar to @B2D235   

Prior to this I had installed/uninstalled various versions of Visual Studio so my OS may not be in the best state.

In any case, I worked around the freeze by changing to targeting 3.5 instead of 2.0.  I'm sure there are going to be negative ramifications to this, but it at least allows me use Code for the moment.   

https://github.com/MannyC/VSCode/commit/ff1a1391687f2370a98415a3f61dc424d4c82627

**Comment by reapazor** [comment]
Hmm it could be an issue of your local machine not having a 2.0 version of mono to compile against. The reason its set to 2.0 is specifically so that Unity's limitations are abided by.

**Comment by MannyC** [comment]
Yeah, I agree, and I'm not suggesting this as a change, simply as a work around if it happens to others.

I did look into trying to check on/install 2.0 if it isn't there, but because it's installed by default in Windows 7, MS don't make it easy to do (I did find instructions on MSDN, but they didn't work).

**Comment by Naxum** [comment]
This is happening to me in Unity 5.2.2, VSCode 0.10.2, and I went and downloaded and install the latest Mono, Mono 2.0 and the latest Mono 2.x. Omnisharp fire icon never appears, autocomplete is incorrect, and only one .sln file is being generated (project.sln, no CSharp in the name).
