### ISSUE TITLE
Code colorization

### ISSUE THREAD

**Issue by bugslife** [dotBunny/VSCode#29]
Hello,

This is not an issue but I was wondering if there is a way for the syntax highlighting to color class names specifically?

Thanks!

**Comment by reapazor** [comment]
TBH Not sure on that one ... 

I know that with the 0.9+ release of Visual Studio Code they allowed for custom colouring, I'll have a quick peek this weekend about this request, as I too could see the use in namespace/class names having something to tell them apart.

**Comment by bugslife** [comment]
Thanks a lot!

**Comment by nosick** [comment]
![2015-10-28 14 07 54](https://cloud.githubusercontent.com/assets/4725570/10786789/5389ac30-7d7d-11e5-8639-8ce2755bb1df.png)

https://www.dropbox.com/s/5tm18kbb0hita9h/csharp.zip?dl=0

unpack in /Users/USERNAME/.vscode/

**Comment by bugslife** [comment]
Awesome man thanks!!

**Comment by Taugeshtu** [comment]
Due to some regexp errors it considered IEnumerable<float> param inside method declaration as god knows what (looked like punctuation on default dark scheme xD ) Fixed the problem, here's csharp language definition I use:
https://onedrive.live.com/redir?resid=BFBDABA12D729DA5!66623&authkey=!AKKf87Vqjxdfh38&ithint=file%2czip

**Comment by bugslife** [comment]
Great, and thanks again!

**Comment by reapazor** [comment]
Looks like upcoming version of Code does this :) I'll close the issue when I confirm upon public release.

**Comment by bugslife** [comment]
Excellent mate!
