### ISSUE TITLE
Create an asset package for the addon

### ISSUE THREAD

**Issue by DDReaper** [dotBunny/VSCode#6]
To ease install, it should be possible to install the addon though an asset package. 
It's easy enough to create and then can be either hosted as a download / release on the GitHub page or uploaded to the asset store.

**Comment by reapazor** [comment]
Another great idea, however one of my issues here is maintaining the package.

Because I use the plugin so often, I'm constantly iterating with it and in its infancy people are nicely pointing out issues. Putting it up on the Asset Store at the moment would limit how fast I could push out updates, specifically their review process takes a couple days.

Once its a bit more stable, I will probably bundle up something for people ... end of the summer more then likely.

**Comment by DDReaper** [comment]
Doesn't have to go on the asset store straight away, just wait for the 1.0 of VsCode for that.
Keep the asset store version in line with the major releases of VsCode and keep the minor version updates as a download.
As you're in the inside track for VsCode, that will help with planning that. (plus it'll be linked in the VsCode docs)

**Comment by reapazor** [comment]
Agreed, that sounds like a decent plan.

I also know that the debugging interface is going to evolve in the future, so I'm somewhat waiting to see how that plays out.

**Comment by reapazor** [comment]
<img width="810" alt="screenshot 2015-09-03 20 18 40" src="https://cloud.githubusercontent.com/assets/99292/9673999/00769d7a-5279-11e5-8b93-a72349b598ca.png">

This is just the draft :) 5 minute art FTW

**Comment by DDReaper** [comment]
5.2??  5.1 should do it surely?
Also make sure you have links to your videos.

**Comment by reapazor** [comment]
Here highlights a short coming with Unity ... I dont have any 5.1 installed on my system at the moment, and they use the version you submit the package with as the requirement ... *sigh*

I'll probably email the AS managers about that.

**Comment by reapazor** [comment]
<img width="807" alt="screenshot 2015-09-04 09 36 40" src="https://cloud.githubusercontent.com/assets/99292/9684885/77cdf7be-52e8-11e5-8c3c-56479ed750c6.png">

Oh its ready :)

**Comment by reapazor** [comment]
Submitted to AS store for review with comment about lowering the requirement.

**Comment by DDReaper** [comment]
Only other issue is that it requires VS 0.8.  Tried with 0.7 and it throws up lots of omnisharp errors.
Just put a notes in the text about it working on 5.0+

**Comment by reapazor** [comment]
Doh forgot about VS 0.8 not being out yet, then again ... its gonna be soon :) i'll put a note in about that.

**Comment by DDReaper** [comment]
Tested with a clean build of 0.8.0
It's all good.

Now don't forget to mention the asset on the GitHub front page with link and update the VSCode guys :D

**Comment by DDReaper** [comment]
Just tried searching on the asset store, not visible yet.
Now that 0.8.0 is out, can this be made live?

**Comment by reapazor** [comment]
Its been in review since the day i posted that pic from prior .... #UASFail

**Comment by DDReaper** [comment]
rofl.
Well I just posted my article on the VSCode 0.8.0 update, also featuring your asset :D
http://darkgenesis.zenithmoon.com/vscode-and-unity-take-another-bold-step-forward/
If you want specifically naming in it, just let me know via the blog contact page .

As soon as the asset package is live, I'll update the article with the link.

**Comment by DDReaper** [comment]
Any update @reapazor on the asset package, still not showing up on the asset store?

**Comment by reapazor** [comment]
Still no review ;/ i have updates I want to post, but dont want to reset the process.

*sigh*

**Comment by reapazor** [comment]
Hi there,

Thanks very much for your submission to the Asset Store.

We ask that you include documentation in the format of .pdf, txt or rtf with your submission, as it is mandatory for all script packages and projects. Create a set up guide with a step-by step tutorial (video or pdf), as well as a script reference if users will need to do any coding.

In order to make this package available to users running 5.1.X it needs to be submitted from a 5.1 Editor.  We can't change it on our end.  You can download older versions of Unity from http://unity3d.com/get-unity/download/archive.

Reply to this email after you have resubmitted this package and we will prioritize its review.

We look forward to your resubmission.


Kind regards,

The Asset Store Team
Unity Technologies

**Comment by reapazor** [comment]
*Sigh* 

Documentation ... its right in the description / video on the asset.
I don't want to download an older version ... seriously... they make it hard for people to do nice things.

**Comment by mbaker3** [comment]
Ugh, what a pain. I've been lurking but keep it up! You're doing noble work here :)

**Comment by DDReaper** [comment]
Well, if you want I can create the asset for earlier versions as I seem to be running with 3 concurrent versions :D.
Just shout @reapazor and I'll create it based on the current check-in or tag.

**Comment by reapazor** [comment]
![howto](https://cloud.githubusercontent.com/assets/99292/10050140/d7896e4a-61e8-11e5-8933-2996697835c8.jpg)
:)

**Comment by DDReaper** [comment]
Looks good, but still not seeing the asset on the store?

What page is that, obviously the Asset menu is different from you're version, have Unity done something?

**Comment by reapazor** [comment]
I submitted for review again, including that help file.

As for the Asset menu, thats taken in 5.2 I believe.

**Comment by DDReaper** [comment]
Not seen it in 5.2 and I use that regularly
SO have you altered your integration to add that new feature?.

**Comment by DDReaper** [comment]
WhooHooo, It's live on the asset store, found it tonight

**Comment by reapazor** [comment]
Ya it looks like at times it doesnt update the editor... im looking into it as a bug to fix by the time i release 2.0 of the integration.

**Comment by DDReaper** [comment]
Ok, but best to pull the existing one, else most will think it will be the same :S, unless you manage to update it to make it work.
