### ISSUE TITLE
Debugger connects and immediately disconnects.

### ISSUE THREAD

**Issue by zsculpt** [dotBunny/VSCode#63]
This is still a continuing problem, and I'm now no longer able to fix it by deleting the ".vscode" directory files. I have the VSCode debugger installed, as well as the VSCode editor extension and all the boxes checked. The debugger spits out a message in the console that it attached, and then about 3 seconds later it disconnects. Can't hit any breakpoints. :-(  I am running Mac OS 10.10.5, Unity 5.3.1.p4, VSCode 0.10.6 and latest version of VSCode and Debugger plugins.

**Comment by theoxuan** [comment]
Same here
![image](https://cloud.githubusercontent.com/assets/5442563/13374452/407ddaaa-ddc0-11e5-9f04-628c116bbced.png)

**Comment by fsommar** [comment]
I'm having the exact same problem with Unity 5.3.2f1 and OS X 10.11.3.

I've updated VSCode and the Debugger plugins and deleted .vscode, but no changes.

**Comment by ru-ace** [comment]
Hi!
At this moment it buggy when setting AllowAttachedDebuggingOfEditor to true
I think this is because Unity want restart after change this settings, but i don't dig deeper.

So easy solution is to open VSCode/Plugins/Editor/VSCode.cs find all EditorPrefs.SetBool("AllowAttachedDebuggingOfEditor" and comment it.
After that restart unity and enable Preferences / External Tools / Editor Attaching manually

After that Debug will work perfect.

ps: sorry for my english

**Comment by reapazor** [comment]
I've been able to reproduce this locally today (finally) looking into why tho ;/

**Comment by reapazor** [comment]
So ... here is the problem:

When Unity has "Editor Attaching" it needs to restart with that option on, however in the VSCode Plugin, I have a feature that reverses the settings that we make when its on, when exiting the editor.  So its kinda like an infinite problem ... so I'm going to push an update that doesnt revert that one setting :)

**Comment by theoxuan** [comment]
Thanks. Hope it’ll be done soon.

**Comment by reapazor** [comment]
It was done within 5 minutes of that post :)
